title: Shannon M. Gross
description: > # this means to ignore newlines until "baseurl:"
  This site contains content related to data science, WASH, and public health
  by Shannon M.Gross, a recent graduate of the Engingeering and Policy Analysis
  program at TU Delft.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shannon M. Gross # add your name
author-img: shannon-gross.png # add your photo
about-author: Hi, I'm Shannon, an engineer and computer science enthusiast. This site contains my thoughts on using technology to improve global public health around the world. Read more <a href="/about">About me</a>. 
social-twitter: shannonmgross
social-facebook: # add your Facebook handle
social-github: shannongross # add your Github handle
social-linkedin: shannonmgross # add your Linkedin handle
social-email: shannon-gross@outlook.com # add your Email address

# Disqus
# discus-identifier: shannongrss # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
